name: Test and Publish

on: [push]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
      
  publish:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Login
        run: cargo login ${{secrets.CARGO_TOKEN}}
      - name: Publish core
        run: cd ./fire-rs-core && cargo publish && cd .. || true
      - name: Publish wrapper
        run: cargo publish
